version = 0.1

[sam-config-env.deploy.parameters]
stack_name = "aws-lambda-crawler"
resolve_s3 = true
s3_prefix = "aws-lambda-crawler"
region = "ap-southeast-2"
profile = "my-aws-profile"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.deploy.parameters]
stack_name = "aws-lambda-crawler"
resolve_s3 = true
s3_prefix = "aws-lambda-crawler"
region = "ap-southeast-2"
profile = "my-aws-profile"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
